import Footer from "../components/footer";
import Navbar from "../components/navbar";
import "../styles/globals.css";
import Head from "next/head";
import dynamic from 'next/dynamic';

const ChatBot = dynamic(import('../components/chatbot'), { ssr: false });


function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>CodeaWear.in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
      <Footer />
      <ChatBot />
    </>
  );
}

export default MyApp;
